name: todo_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.4.10
  fluttertoast: ^8.2.4
  hexcolor: ^3.0.1
  hooks_riverpod: ^2.4.10
  http: ^1.2.0
  intl: ^0.19.0
  localstorage: ^4.0.1+4
  riverpod_annotation: ^2.3.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
